resource_rules:
  issues:
    rules:
      - name: Close old needinfo policy
        conditions:
          date:
            attribute: updated_at
            condition: older_than
            interval_type: months
            interval: 1
          state: opened
          labels:
            - needinfo
        limits:
          most_recent: 50
        actions:
          status: close
          comment: |
            {{author}} This issue was marked as needinfo with no update for long time. We are now closing it, but please add the necessary information and re-open if it is still relevant. This is an automated message.

  merge_requests:
    rules:
      - name: Close old WIP policy
        conditions:
          title: WIP
          date:
            attribute: updated_at
            condition: older_than
            interval_type: months
            interval: 3
          state: opened
          labels:
            - No Label
        limits:
          most_recent: 50
        actions:
          status: close
          comment: |
            {{author}} This merge request is marked as work in progress with no update for a long time. We are now closing it, but please re-open if you are still interested in finishing this merge request. This is an automated message.
      - name: Close old policy
        conditions:
          date:
            attribute: updated_at
            condition: older_than
            interval_type: months
            interval: 5
          state: opened
        limits:
          most_recent: 50
        actions:
          status: close
          comment: |
            {{author}} This merge request is open for a long time without an update. We are now closing it, but please re-open if you are still interested in finishing this merge request. This is an automated message.
