services:
  ocserv:
    platform: linux/amd64
    build: .
    image: siegfriedschmidt/ocserv:openssl
    container_name: ocserv
    ports:
      - "443:443/tcp"
      - "443:443/udp"
    environment:
      # Disable auto signed certificates if you already have letsencrypt certs
      - DISABLE_AUTO_SIGNED_CERTS=false
      # Use iptables to forward traffic to your external interface
      - ENABLE_INTERNET=true
      # Set VPN_SUBNET according to your ocserv.conf!
      - VPN_SUBNET=10.10.10.0/24
    volumes:
      - ./config:/etc/ocserv
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    security_opt:
      - no-new-privileges:true
    restart: "no"
