services:
  ocserv:
    platform: linux/amd64
    build: .
    image: siegfriedschmidt/ocserv
    container_name: ocserv
    ports:
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./config:/etc/ocserv
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    security_opt:
      - no-new-privileges:true
    restart: no