services:
  ocserv:
    platform: linux/amd64
    build: .
    image: siegfriedschmidt/ocserv
    container_name: ocserv
    ports:
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      # Mount your host directory with your custom ocserv.conf, certificates, etc.
      - ./config:/etc/ocserv
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    privileged: true
    restart: no